# Generated by Django 2.2 on 2019-10-07 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_heading', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('salary', models.IntegerField(default=10000)),
                ('apply_by', models.DateField()),
                ('job_type', models.CharField(max_length=255)),
                ('available', models.IntegerField()),
                ('about_company', models.TextField()),
                ('about_job', models.TextField()),
                ('skills', models.TextField()),
                ('requirements', models.TextField()),
                ('why_us', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Employers',
        ),
    ]
