# Generated by Django 2.2 on 2019-10-07 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191007_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name': 'Job posted by Employer'},
        ),
    ]
